### ISSUE TITLE
GitHub Actions: Error: Cannot find module 'path-scurry'

### ISSUE THREAD

**Issue by timheerwagen** [isaacs/rimraf#270]
Hello, thank you very much for the great package.

In a GitHub Actions run with the new 5.0.0 version I encounter the following error: `Error: Cannot find module 'path-scurry'`. Locally, however, it works. I also tried clean install, deleting node_modules etc.

Workflow:
```
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: NodeJs aufsetzen
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # NPM ci mit Cache
      - name: Cache dependencies
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build
        run: rimraf dist && tsup
...
```

Error log:
```
• Packages in scope: ...
• Running pre-release in 1 packages
• Remote caching disabled
pre-release: cache miss, executing 3b10509691a05be[4](...#step:7:5)

pre-release: > npm run clean && tsup
pre-release: 
pre-release: 
pre-release: > 
pre-release: > rimraf dist
pre-release: 
pre-release: node:internal/modules/cjs/loader:1078
pre-release:   throw err;
pre-release:   ^
pre-release: 
pre-release: Error: Cannot find module 'path-scurry'
pre-release: Require stack:
pre-release: - /home/runner/work/packages/cms/node_modules/glob/dist/cjs/src/glob.js
pre-release: - /home/runner/work/packages/cms/node_modules/glob/dist/cjs/src/index.js
pre-release: - /home/runner/work/packages/cms/node_modules/rimraf/dist/cjs/src/index.js
pre-release: - /home/runner/work/packages/cms/node_modules/rimraf/dist/cjs/src/bin.js
pre-release:     at Module._resolveFilename (node:internal/modules/cjs/loader:107[5](...#step:7:6):15)
pre-release:     at Module._load (node:internal/modules/cjs/loader:920:27)
pre-release:     at Module.require (node:internal/modules/cjs/loader:1141:19)
pre-release:     at require (node:internal/modules/cjs/helpers:110:18)
pre-release:     at Object.<anonymous> (/home/runner/work/packages/cms/node_modules/glob/dist/cjs/src/glob.js:5:23)
pre-release:     at Module._compile (node:internal/modules/cjs/loader:1254:14)
pre-release:     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
pre-release:     at Module.load (node:internal/modules/cjs/loader:1117:32)
pre-release:     at Module._load (node:internal/modules/cjs/loader:958:12)
pre-release:     at Module.require (node:internal/modules/cjs/loader:1141:19) {
pre-release:   code: 'MODULE_NOT_FOUND',
pre-release:   requireStack: [
pre-release:     '/home/runner/work/packages/cms/node_modules/glob/dist/cjs/src/glob.js',
pre-release:     '/home/runner/work/packages/cms/node_modules/glob/dist/cjs/src/index.js',
pre-release:     '/home/runner/work/packages/cms/node_modules/rimraf/dist/cjs/src/index.js',
pre-release:     '/home/runner/work/packages/cms/node_modules/rimraf/dist/cjs/src/bin.js'
pre-release:   ]
pre-release: }
pre-release: 
pre-release: Node.js v18.1[6](...#step:7:7).0
pre-release: npm ERR! Lifecycle script `clean` failed with error: 
pre-release: npm ERR! Error: command failed 
pre-release: npm ERR!   in workspace: ... 
pre-release: npm ERR!   at location: /home/runner/work/packages/cms 
pre-release: npm ERR! Lifecycle script `pre-release` failed with error: 
pre-release: npm ERR! Error: command failed 
pre-release: npm ERR!   in workspace: ... 
pre-release: npm ERR!   at location: /home/runner/work/packages/cms 
pre-release: ERROR: command finished with error: command (/home/runner/work/packages/cms) npm run pre-release exited (1)
command (/home/runner/work/packages/cms) npm run pre-release exited (1)
 ERROR  run failed: command  exited (1)

 Tasks:    0 successful, 1 total
Cached:    0 cached, 1 total
  Time:    [7](...#step:7:8)2[8](...#step:7:9)ms
```

My current workaround is to use version 4.4.1.
I hope this helps in some way.
